In [1]:
import pandas as pd
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings('ignore')

In [2]:
link = 'Resources/amazon_prime_titles.csv'
amazon_df = pd.read_csv(link)
amazon_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [3]:
amazon_df.drop(columns =['date_added','duration','rating','director','show_id','cast'], inplace = True)
#amazon_tv = amazon_df.loc[amazon_df['type']=='TV Show']

In [4]:
amazon_df.head(15)

,type,title,country,release_year,listed_in,description
0,Movie,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...
1,Movie,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,Movie,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,Movie,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ..."
4,Movie,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
5,Movie,Living With Dinosaurs,United Kingdom,1989,"Fantasy, Kids",The story unfolds in a an English seaside town...
6,Movie,Hired Gun,United States,2017,"Documentary, Special Interest","They are the ""First Call, A-list"" musicians, j..."
7,Movie,Grease Live!,United States,2016,Comedy,"This honest, uncompromising comedy chronicles ..."
8,Movie,Global Meltdown,Canada,2017,"Action, Science Fiction, Suspense",A helicopter pilot and an environmental scient...
9,Movie,David's Mother,United States,1994,Drama,Sally Goodson is a devoted mother to her autis...
10,Movie,Forest Fairies,Canada,2016,"Adventure, Kids",Amanda stumbles upon a hidden village of fairi...
11,Movie,Take Care,United States,2014,Comedy,"When a car crash leaves Frannie immobilized, s..."
12,Movie,The Night Eats The World,France,2018,"Horror, Suspense",After waking up in an apartment the night afte...
13,Movie,Resilencia,Spain,2020,"Documentary, Sports",The documentary follows the midfielder’s every...
14,Movie,Elon Musk: The Real Life Iron Man,United Kingdom,2018,Documentary,"Discover the meteoric rise of Elon Musk, the m..."

In [5]:
amazon_df.dropna(subset = ['country'], inplace = True)
amazon_df

,type,title,country,release_year,listed_in,description
0,Movie,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...
1,Movie,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,Movie,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,Movie,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ..."
4,Movie,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...
9604,Movie,Bride Wars,United States,2009,Comedy,When a clerical error causes a clash in weddin...
9614,Movie,What Happens in Vegas,United States,2008,Comedy,Jack Fuller (Ashton Kutcher) and Joy McNally (...
9641,Movie,Marley & Me,United States,2008,"Comedy, Drama, Kids",Jennifer Aniston and Owen Wilson unleash huge ...
9643,Movie,Love & Other Drugs,United States,2010,"Comedy, Drama",A womanizing pfizer drug rep with no sense of ...
9644,Movie,Little Miss Sunshine,United States,2006,"Comedy, Drama",A family determined to get their young daughte...

In [6]:
amazon_df.dtypes

type            object
title           object
country         object
release_year     int64
listed_in       object
description     object
dtype: object

In [7]:
amazon_movie = amazon_df.loc[amazon_df['type']=='Movie']
amazon_movie

,type,title,country,release_year,listed_in,description
0,Movie,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...
1,Movie,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,Movie,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,Movie,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ..."
4,Movie,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...
9604,Movie,Bride Wars,United States,2009,Comedy,When a clerical error causes a clash in weddin...
9614,Movie,What Happens in Vegas,United States,2008,Comedy,Jack Fuller (Ashton Kutcher) and Joy McNally (...
9641,Movie,Marley & Me,United States,2008,"Comedy, Drama, Kids",Jennifer Aniston and Owen Wilson unleash huge ...
9643,Movie,Love & Other Drugs,United States,2010,"Comedy, Drama",A womanizing pfizer drug rep with no sense of ...
9644,Movie,Little Miss Sunshine,United States,2006,"Comedy, Drama",A family determined to get their young daughte...

In [8]:
amazon_movie.dropna(subset = ['country'], inplace = True)

In [9]:
amazon_movie.drop(columns=['type'],inplace = True)

###### amazon_movie.rename(columns = {'listed_in':'genre'}, inplace = True)
amazon_movie

In [10]:
amazon_movie.rename(columns={'listed_in':'genre','cast':"movie_cast"}, inplace =True)
amazon_movie

,title,country,release_year,genre,description
0,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...
1,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ..."
4,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...
9604,Bride Wars,United States,2009,Comedy,When a clerical error causes a clash in weddin...
9614,What Happens in Vegas,United States,2008,Comedy,Jack Fuller (Ashton Kutcher) and Joy McNally (...
9641,Marley & Me,United States,2008,"Comedy, Drama, Kids",Jennifer Aniston and Owen Wilson unleash huge ...
9643,Love & Other Drugs,United States,2010,"Comedy, Drama",A womanizing pfizer drug rep with no sense of ...
9644,Little Miss Sunshine,United States,2006,"Comedy, Drama",A family determined to get their young daughte...

In [11]:
amazon_movie['Streaming Service']='Amazon'
amazon_movie

,title,country,release_year,genre,description,Streaming Service
0,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...,Amazon
1,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon
2,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon
3,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon
4,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon
...,...,...,...,...,...,...
9604,Bride Wars,United States,2009,Comedy,When a clerical error causes a clash in weddin...,Amazon
9614,What Happens in Vegas,United States,2008,Comedy,Jack Fuller (Ashton Kutcher) and Joy McNally (...,Amazon
9641,Marley & Me,United States,2008,"Comedy, Drama, Kids",Jennifer Aniston and Owen Wilson unleash huge ...,Amazon
9643,Love & Other Drugs,United States,2010,"Comedy, Drama",A womanizing pfizer drug rep with no sense of ...,Amazon
9644,Little Miss Sunshine,United States,2006,"Comedy, Drama",A family determined to get their young daughte...,Amazon

In [13]:
amazon_movie.to_csv('Finalized CSV/Amazon_movies.csv',index = False, header = True)

In [15]:
connection_string = "postgres:postgres@localhost:5432/Project_2_movies"
engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
premise_transformed.to_sql(name='premise', con=engine, if_exists='append', index=True)