In [1]:
import pandas as pd
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings('ignore')

In [2]:
amazon_link = 'Finalized CSV/Amazon_movies.csv'
disney_link = 'Finalized CSV/Disney_movies.csv'
hulu_link = 'Finalized CSV/hulu_movies.csv'
netflix_link = 'Finalized CSV/netflix_movies.csv'

In [15]:
amazon_df = pd.read_csv(amazon_link)
disney_df = pd.read_csv(disney_link)
hulu_df = pd.read_csv(hulu_link)
netflix_df = pd.read_csv(netflix_link)

In [12]:
ama_dis = amazon_df.merge(disney_df, how='outer')
ama_dis

,title,country,release_year,genre,description,Streaming Service
0,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...,Amazon
1,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon
2,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon
3,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon
4,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon
...,...,...,...,...,...,...
1510,X-Men Origins: Wolverine,"United States, United Kingdom",2009,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...,Disney
1511,Night at the Museum: Battle of the Smithsonian,"United States, Canada",2009,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...,Disney
1512,Eddie the Eagle,"United Kingdom, Germany, United States",2016,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",Disney
1513,Bend It Like Beckham,"United Kingdom, Germany, United States",2003,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,Disney
1514,Captain Sparky vs. The Flying Saucers,United States,2012,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.,Disney

In [16]:
ama_dis_hulu = ama_dis.merge(hulu_df, how='outer')
ama_dis_hulu

,title,country,release_year,genre,description,Streaming Service
0,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...,Amazon
1,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon
2,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon
3,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon
4,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon
...,...,...,...,...,...,...
2171,All Saints (1998),Australia,1998,"Drama, International",All Saints is an Australian medical drama focu...,hulu
2172,Getting On,United Kingdom,2009,"Comedy, International, Sitcom",Care for the elderly is the least glamorous ar...,hulu
2173,(Sub) Ninja Scroll,Japan,1993,"Action, Adult Animation, Adventure",When Jubei saves a young ninja woman from the ...,hulu
2174,Packed to the Rafters,Australia,2008,"Comedy, Drama, International",Packed to the Rafters is an Australian family-...,hulu
2175,Amy Winehouse: A Final Goodbye,United Kingdom,2011,"Documentaries, Music",A Final Goodbye is an intimate look into the l...,hulu

In [17]:
total_merge = ama_dis_hulu.merge(netflix_df, how='outer')
total_merge

,title,country,release_year,genre,description,Streaming Service
0,The Grand Seduction,Canada,2014,"Comedy, Drama",A small fishing village must procure a local d...,Amazon
1,Take Care Good Night,India,2018,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon
2,Secrets of Deception,United States,2017,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon
3,Pink: Staying True,United States,2014,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon
4,Monster Maker,United Kingdom,1989,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon
...,...,...,...,...,...,...
7862,Zinzana,"United Arab Emirates, Jordan",2015,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,netflix
7863,Zodiac,United States,2007,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",netflix
7864,Zombieland,United States,2009,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,netflix
7865,Zoom,United States,2006,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",netflix
7866,Zubaan,India,2015,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,netflix

In [18]:
total_merge.to_csv('Finalized CSV/total_merge.csv',index = False, header = True)